export const HeadingTheme = {
  sizes: {
    "2XL": {
      fontSize: "60px",
      fontKerning: "-10px",
      letterSpacing: "65",
      fontWeight: "900",
      cursor: "default",
      caretColor: "transparent",
    },
    XL: {
      fontSize: "40px",
      fontKerning: "-10px",
      letterSpacing: "-0.4px",
      lineheight: "45",
      fontWeight: "900",
      cursor: "default",
      caretColor: "transparent",
    },
    lg: {
      fontSize: "30px",
      fontKerning: "-25px",
      letterSpacing: "35",
      fontWeight: "700",
      cursor: "default",
      caretColor: "transparent",
    },
    md: {
      fontSize: "24px",
      fontKerning: "-25px",
      letterSpacing: "25",
      fontWeight: "700",
      cursor: "default",
      caretColor: "transparent",
    },
    sm: {
      fontSize: "20px",
      fontKerning: "-10px",
      letterSpacing: "22",
      fontWeight: "900",
      cursor: "default",
      caretColor: "transparent",
    },
    xs: {
      fontSize: "14px",
      fontKerning: "-25px",
      letterSpacing: "16",
      fontWeight: "700",
      cursor: "default",
      caretColor: "transparent",
    },
  },
};
