export const TextTheme = {
  textButton: {
    fontWeight: 'bold',
    fontSize: '16px',
    letterSpacing: '0px',
    lineSpacing: '21',
    cursor: 'default',
    caretColor: 'transparent',
  },
  '2XL': {
    fontSize: '40px',
    fontKerning: '0px',
    letterSpacing: '0px',
    fontWeight: 'regular',
    cursor: 'default',
    caretColor: 'transparent',
  },
  XL: {
    fontSize: '20px',
    fontKerning: '0px',
    letterSpacing: '32',
    fontWeight: 'regular',
    cursor: 'default',
    caretColor: 'transparent',
  },
  lg: {
    fontSize: '16px',
    fontKerning: '-10px',
    letterSpacing: '18',
    fontWeight: 'medium',
    cursor: 'default',
    caretColor: 'transparent',
  },
  md: {
    fontSize: '14px',
    fontKerning: '-0px',
    letterSpacing: '19',
    fontWeight: 'regular',
    cursor: 'default',
    caretColor: 'transparent',
  },
  sm: {
    fontSize: '12px',
    fontKerning: '0px',
    letterSpacing: '16',
    fontWeight: 'medium',
    cursor: 'default',
    caretColor: 'transparent',
  },
  xs: {
    fontSize: '10px',
    fontKerning: '0px',
    letterSpacing: '13',
    fontWeight: 'medium',
    cursor: 'default',
    caretColor: 'transparent',
  },
};
